version: '2'
services:
    db: 
        platform: linux/x86_64
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_ROOT_PASSWORD: docker
        volumes: # Comment / Uncomment for persistent mysql data
            - my-datavolume:/var/lib/mysql:delegated # Comment / Uncomment for persistent mysql data

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_USER: docker # Comment / Uncomment for automatic login
            PMA_PASSWORD: docker # Comment / Uncomment for automatic login
            UPLOAD_LIMIT: 1000M

    app: 
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        ports: 
            - "3001:3000"
        depends_on:
            - db
        links:
            - db
        environment:
            DB_USER: docker
            DB_NAME: docker
            DB_PASSWORD: docker
            DB_HOST: db


volumes: # Comment / Uncomment for persistent mysql data
    my-datavolume: # Comment / Uncomment for persistent mysql data
